//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioCuentaUsuario
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaCompleta", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCuentaUsuario")]
    public partial class CuentaCompleta : object
    {
        
        private int Genero_idGeneroField;
        
        private string contrasenaField;
        
        private string correoField;
        
        private int idCuentaField;
        
        private int idFotoCuentaUsuarioField;
        
        private string nombreUsuarioField;
        
        private string telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Genero_idGenero
        {
            get
            {
                return this.Genero_idGeneroField;
            }
            set
            {
                this.Genero_idGeneroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena
        {
            get
            {
                return this.contrasenaField;
            }
            set
            {
                this.contrasenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCuenta
        {
            get
            {
                return this.idCuentaField;
            }
            set
            {
                this.idCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFotoCuentaUsuario
        {
            get
            {
                return this.idFotoCuentaUsuarioField;
            }
            set
            {
                this.idFotoCuentaUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario
        {
            get
            {
                return this.nombreUsuarioField;
            }
            set
            {
                this.nombreUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCuentaUsuario.IServicioCuentaUsuario")]
    public interface IServicioCuentaUsuario
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCuentaUsuario/IniciarSesion", ReplyAction="http://tempuri.org/IServicioCuentaUsuario/IniciarSesionResponse")]
        ServicioCuentaUsuario.CuentaCompleta IniciarSesion(string correo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCuentaUsuario/IniciarSesion", ReplyAction="http://tempuri.org/IServicioCuentaUsuario/IniciarSesionResponse")]
        System.Threading.Tasks.Task<ServicioCuentaUsuario.CuentaCompleta> IniciarSesionAsync(string correo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCuentaUsuario/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioCuentaUsuario/RegistrarUsuarioResponse")]
        int RegistrarUsuario(string nombreUsuario, string correo, string contrasena, string telefono, int idFotoCuentaUsuario, int Genero_idGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCuentaUsuario/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioCuentaUsuario/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<int> RegistrarUsuarioAsync(string nombreUsuario, string correo, string contrasena, string telefono, int idFotoCuentaUsuario, int Genero_idGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCuentaUsuario/ModificarUsuario", ReplyAction="http://tempuri.org/IServicioCuentaUsuario/ModificarUsuarioResponse")]
        int ModificarUsuario(int idCuenta, string nombreUsuario, string correo, string contrasena, string telefono, int idFotoCuentaUsuario, int Genero_idGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCuentaUsuario/ModificarUsuario", ReplyAction="http://tempuri.org/IServicioCuentaUsuario/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<int> ModificarUsuarioAsync(int idCuenta, string nombreUsuario, string correo, string contrasena, string telefono, int idFotoCuentaUsuario, int Genero_idGenero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCuentaUsuario/validarExistencia", ReplyAction="http://tempuri.org/IServicioCuentaUsuario/validarExistenciaResponse")]
        int validarExistencia(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCuentaUsuario/validarExistencia", ReplyAction="http://tempuri.org/IServicioCuentaUsuario/validarExistenciaResponse")]
        System.Threading.Tasks.Task<int> validarExistenciaAsync(string nombreUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServicioCuentaUsuarioChannel : ServicioCuentaUsuario.IServicioCuentaUsuario, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServicioCuentaUsuarioClient : System.ServiceModel.ClientBase<ServicioCuentaUsuario.IServicioCuentaUsuario>, ServicioCuentaUsuario.IServicioCuentaUsuario
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioCuentaUsuarioClient() : 
                base(ServicioCuentaUsuarioClient.GetDefaultBinding(), ServicioCuentaUsuarioClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioCuentaUsuario.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCuentaUsuarioClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioCuentaUsuarioClient.GetBindingForEndpoint(endpointConfiguration), ServicioCuentaUsuarioClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCuentaUsuarioClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioCuentaUsuarioClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCuentaUsuarioClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioCuentaUsuarioClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCuentaUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicioCuentaUsuario.CuentaCompleta IniciarSesion(string correo, string contrasena)
        {
            return base.Channel.IniciarSesion(correo, contrasena);
        }
        
        public System.Threading.Tasks.Task<ServicioCuentaUsuario.CuentaCompleta> IniciarSesionAsync(string correo, string contrasena)
        {
            return base.Channel.IniciarSesionAsync(correo, contrasena);
        }
        
        public int RegistrarUsuario(string nombreUsuario, string correo, string contrasena, string telefono, int idFotoCuentaUsuario, int Genero_idGenero)
        {
            return base.Channel.RegistrarUsuario(nombreUsuario, correo, contrasena, telefono, idFotoCuentaUsuario, Genero_idGenero);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarUsuarioAsync(string nombreUsuario, string correo, string contrasena, string telefono, int idFotoCuentaUsuario, int Genero_idGenero)
        {
            return base.Channel.RegistrarUsuarioAsync(nombreUsuario, correo, contrasena, telefono, idFotoCuentaUsuario, Genero_idGenero);
        }
        
        public int ModificarUsuario(int idCuenta, string nombreUsuario, string correo, string contrasena, string telefono, int idFotoCuentaUsuario, int Genero_idGenero)
        {
            return base.Channel.ModificarUsuario(idCuenta, nombreUsuario, correo, contrasena, telefono, idFotoCuentaUsuario, Genero_idGenero);
        }
        
        public System.Threading.Tasks.Task<int> ModificarUsuarioAsync(int idCuenta, string nombreUsuario, string correo, string contrasena, string telefono, int idFotoCuentaUsuario, int Genero_idGenero)
        {
            return base.Channel.ModificarUsuarioAsync(idCuenta, nombreUsuario, correo, contrasena, telefono, idFotoCuentaUsuario, Genero_idGenero);
        }
        
        public int validarExistencia(string nombreUsuario)
        {
            return base.Channel.validarExistencia(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<int> validarExistenciaAsync(string nombreUsuario)
        {
            return base.Channel.validarExistenciaAsync(nombreUsuario);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCuentaUsuario))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCuentaUsuario))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/ServiciosCuentaUsuario/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioCuentaUsuarioClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioCuentaUsuario);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioCuentaUsuarioClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioCuentaUsuario);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioCuentaUsuario,
        }
    }
}
