-- MySQL Script generated by MySQL Workbench
-- Wed Jan 27 15:12:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema estado
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `estado` ;

-- -----------------------------------------------------
-- Schema estado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estado` DEFAULT CHARACTER SET utf8 ;
USE `estado` ;

-- -----------------------------------------------------
-- Table `estado`.`usuarioestado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado`.`usuarioestado` ;

CREATE TABLE IF NOT EXISTS `estado`.`usuarioestado` (
  `idUsuarioEstado` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuarioEstado`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estado`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado`.`estado` ;

CREATE TABLE IF NOT EXISTS `estado`.`estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `UsuarioEstado_idUsuarioEstado` INT NOT NULL,
  `idEstadoImagen` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idEstado`),
  INDEX `fk_Estado_UsuarioEstado_idx` (`UsuarioEstado_idUsuarioEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Estado_UsuarioEstado`
    FOREIGN KEY (`UsuarioEstado_idUsuarioEstado`)
    REFERENCES `estado`.`usuarioestado` (`idUsuarioEstado`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estado`.`reaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado`.`reaccion` ;

CREATE TABLE IF NOT EXISTS `estado`.`reaccion` (
  `idReaccion` INT NOT NULL AUTO_INCREMENT,
  `nombreReaccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReaccion`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estado`.`estado_has_reaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado`.`estado_has_reaccion` ;

CREATE TABLE IF NOT EXISTS `estado`.`estado_has_reaccion` (
  `Estado_idEstado` INT NOT NULL,
  `Reaccion_idReaccion` INT NOT NULL,
  `nombreUsuario` VARCHAR(100) NULL DEFAULT NULL,
  INDEX `fk_Estado_has_Reaccion_Reaccion1_idx` (`Reaccion_idReaccion` ASC) VISIBLE,
  INDEX `fk_Estado_has_Reaccion_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Estado_has_Reaccion_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `estado`.`estado` (`idEstado`),
  CONSTRAINT `fk_Estado_has_Reaccion_Reaccion1`
    FOREIGN KEY (`Reaccion_idReaccion`)
    REFERENCES `estado`.`reaccion` (`idReaccion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `estado`.`tipoestado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado`.`tipoestado` ;

CREATE TABLE IF NOT EXISTS `estado`.`tipoestado` (
  `idTipoEstado` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idTipoEstado`),
  INDEX `fk_TipoEstado_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_TipoEstado_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `estado`.`estado` (`idEstado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
