-- MySQL Script generated by MySQL Workbench
-- Fri Jan 22 01:58:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `whats_cuentasdeusuario` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `whats_cuentasdeusuario` DEFAULT CHARACTER SET utf8 ;
USE `whats_cuentasdeusuario` ;

-- -----------------------------------------------------
-- Table `mydb`.`Contrasena`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whats_cuentasdeusuario`.`Contrasena` (
  `idContrasena` INT NOT NULL AUTO_INCREMENT,
  `contrasena` VARCHAR(200) NOT NULL,
  `Cuenta_idCuenta` INT NOT NULL,
  PRIMARY KEY (`idContrasena`),
  INDEX `fk_Contrasena_Cuenta1_idx` (`Cuenta_idCuenta` ASC) VISIBLE,
  CONSTRAINT `fk_Contrasena_Cuenta1`
    FOREIGN KEY (`Cuenta_idCuenta`)
    REFERENCES `whats_cuentasdeusuario`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Correo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whats_cuentasdeusuario`.`Correo` (
  `idCorreo` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(100) NOT NULL,
  `Cuenta_idCuenta` INT NOT NULL,
  PRIMARY KEY (`idCorreo`),
  INDEX `fk_Correo_Cuenta_idx` (`Cuenta_idCuenta` ASC) VISIBLE,
  CONSTRAINT `fk_Correo_Cuenta`
    FOREIGN KEY (`Cuenta_idCuenta`)
    REFERENCES `whats_cuentasdeusuario`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whats_cuentasdeusuario`.`Cuenta` (
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(100) NOT NULL,
  `idFotoCuentaUsuario` INT NULL,
  `Genero_idGenero` INT NOT NULL,
  PRIMARY KEY (`idCuenta`),
  INDEX `fk_Cuenta_Genero1_idx` (`Genero_idGenero` ASC) VISIBLE,
  CONSTRAINT `fk_Cuenta_Genero1`
    FOREIGN KEY (`Genero_idGenero`)
    REFERENCES `whats_cuentasdeusuario`.`Genero` (`idGenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whats_cuentasdeusuario`.`Genero` (
  `idGenero` INT NOT NULL AUTO_INCREMENT,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whats_cuentasdeusuario`.`Telefono` (
  `idTelefono` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(20) NOT NULL,
  `Cuenta_idCuenta` INT NOT NULL,
  PRIMARY KEY (`idTelefono`),
  INDEX `fk_Telefono_Cuenta1_idx` (`Cuenta_idCuenta` ASC) VISIBLE,
  CONSTRAINT `fk_Telefono_Cuenta1`
    FOREIGN KEY (`Cuenta_idCuenta`)
    REFERENCES `whats_cuentasdeusuario`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
