-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 19:19:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Multimedia
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Multimedia` ;

-- -----------------------------------------------------
-- Schema Multimedia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Multimedia` DEFAULT CHARACTER SET utf8 ;
USE `Multimedia` ;

-- -----------------------------------------------------
-- Table `Multimedia`.`Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Multimedia`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `Multimedia`.`Direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idDireccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Multimedia`.`FotoCuentaUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Multimedia`.`FotoCuentaUsuario` ;

CREATE TABLE IF NOT EXISTS `Multimedia`.`FotoCuentaUsuario` (
  `idFotoCuentaUsuario` INT NOT NULL AUTO_INCREMENT,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idFotoCuentaUsuario`),
  INDEX `fk_FotoCuentaUsuario_Direccion1_idx` (`Direccion_idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_FotoCuentaUsuario_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `Multimedia`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Multimedia`.`EstadoImagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Multimedia`.`EstadoImagen` ;

CREATE TABLE IF NOT EXISTS `Multimedia`.`EstadoImagen` (
  `idEstadoImagen` INT NOT NULL AUTO_INCREMENT,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idEstadoImagen`),
  INDEX `fk_EstadoImagen_Direccion1_idx` (`Direccion_idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_EstadoImagen_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `Multimedia`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Multimedia`.`MensajeImagen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Multimedia`.`MensajeImagen` ;

CREATE TABLE IF NOT EXISTS `Multimedia`.`MensajeImagen` (
  `idMensajeImagen` INT NOT NULL AUTO_INCREMENT,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idMensajeImagen`),
  INDEX `fk_MensajeImagen_Direccion_idx` (`Direccion_idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_MensajeImagen_Direccion`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `Multimedia`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Multimedia`.`MensajeAudio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Multimedia`.`MensajeAudio` ;

CREATE TABLE IF NOT EXISTS `Multimedia`.`MensajeAudio` (
  `idMensajeAudio` INT NOT NULL AUTO_INCREMENT,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idMensajeAudio`),
  INDEX `fk_MensajeAudio_Direccion1_idx` (`Direccion_idDireccion` ASC) VISIBLE,
  CONSTRAINT `fk_MensajeAudio_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `Multimedia`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
